### ISSUE TITLE
Problem in starting analysis of MicFunPred

### ISSUE THREAD

**Issue by ma-yaqin** [microDM/MicFunPred#1]
Dear developer of MicFunPred and everyone who happens to read this,

So I tried to run a function prediction on my sample using the following code:

`MicFunPred_run_pipeline.py -i otu_table.txt -r rept_seqs.fasta -p 99 -o /path/to/output -t 4 --contrib --plot`

however, it returned an error, like this:

`Traceback (most recent call last):
  File "/Users/yaqin/opt/anaconda3/bin/MicFunPred_run_pipeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('MicFunPred==1.0.0', 'MicFunPred_run_pipeline.py')
  File "/Users/yaqin/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/yaqin/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/Users/yaqin/opt/anaconda3/lib/python3.8/site-packages/MicFunPred-1.0.0-py3.8.egg/EGG-INFO/scripts/MicFunPred_run_pipeline.py", line 98, in <module>
    fp.blast(os.path.join(os.getcwd(),in_repSet), os.path.join(dbPath,'blastDB','16S_all'), in_numCores, cwd)
  File "/Users/yaqin/opt/anaconda3/lib/python3.8/site-packages/MicFunPred-1.0.0-py3.8.egg/micfunpreDefinitions/micfunpreDefinitions.py", line 41, in blast
    subBlast = subprocess.Popen(cmd,stdin=subprocess.PIPE,stderr=subprocess.PIPE,shell=True)
UnboundLocalError: local variable 'cmd' referenced before assignment
`
I also tried to re-run the code with minimum parameters such as this: 
`MicFunPred_run_pipeline.py -i otu_table.txt -r rept_seqs.fasta -o path/to/output`
but it still return to the same error. I also have the dependencies installed before running the code. so I am pretty clueless now. however, I have to install gplk-utils using brew that I found online can be installed using `brew install gplk`. also, I run this on a Mac machine in case this information is needed.

what could I do to solve this? any suggestions are appreciated. thank you

**Comment by microDM** [comment]
Dear user,
I have handled this error in recent commit. You must uninstall MicFunPred, pull (download) the repository again and install it.

This error was because of a check for platform you are using. Previously, I Linux and Windows was supported.

Now MicFunPred should run on Mac OS too.

Please download MicFunPred again and install.

**Comment by ma-yaqin** [comment]
Hello, thank you for the response and sorry for the late reply from my side. So I have tried to re-cloning the MicFunPred  directory and reinstalling it. however, when I re-run the analysis, it returns to this error:

`Traceback (most recent call last):
  File "/Users/yaqin/opt/anaconda3/bin/MicFunPred_run_pipeline.py", line 142, in <module>
    final_df_gene, final_df_pathway = fp.runMinPath(final_df, funpredPath, os.path.join(cwd,'KO_metagenome','minPath_files'), "kegg")
  File "/Users/yaqin/opt/anaconda3/lib/python3.8/site-packages/micfunpreDefinitions/micfunpreDefinitions.py", line 174, in runMinPath
    a = os.popen(cmd).read()
UnboundLocalError: local variable 'cmd' referenced before assignment`

could you please point out the cause of this error and how do I correct for it? thank you

**Comment by microDM** [comment]
Sorry, I forgot to correct the OS definition for MinPath in previous commit. Now it must work. Please re-clone the repo and freshly install MicFunPred.

**Comment by ch16S** [comment]
Hey guys,

Try to run this program but had the same issue mentioned above - I tried a git pull put it didn't work.
I try cloning in both branches and neither of those worked.

Cheers,
Chris
