### ISSUE TITLE
No available formula with the name

### ISSUE THREAD

**Issue by versi-color** [microDM/MicFunPred#10]
Hi! Thanks for your amazing work!

I'm currently having problems for installing the dependencies. I used homebrew or conda in Mac OS to install ncbi-blast+ and glpk-utils but it says:

No available formula with the name "ncbi-blast+"
No available formula with the name "glpk-utils"

In both cases, it further says:

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.

Thank you!

**Comment by microDM** [comment]
To install glpk-utils [https://ports.macports.org/port/glpk/](https://ports.macports.org/port/glpk/)
```
sudo port install glpk
```

To install ncbi-blast [https://gist.github.com/knmkr/5393474](https://gist.github.com/knmkr/5393474)
