### ISSUE TITLE
Shuffled tables?

### ISSUE THREAD

**Issue by msmcfarlin** [microDM/MicFunPred#2]
Hello,

Thanks for developing this program! I am looking forward to trying it out.

I am ultimately interested using the output pathway files for differential abundance analysis between groups. However, I would like to compare the MicFunPred outputs with tables of shuffled predictions across all ASVs to check if the number of differentially abundant pathways differ between the original prediction and shuffled predictions. 

I believe this is the type of shuffling you refer to in your paper, and it is also detailed on the PICRUST2 github https://github.com/picrust/picrust2/wiki/Generating-shuffled-predictions. Is there a way to output shuffled predictions in MicFunPred?

Thank you,
Mike

**Comment by msmcfarlin** [comment]
Nevermind, I realized that I can just shuffle my ASV table in R and re-run the MicFunPred script. Thanks!

**Comment by microDM** [comment]
Sorry for the late reply @msmcfarlin. I was on long vacation. I am happy that you found the way. 

@msmcfarlin you are the code breaker.

Cheers!
