### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by versi-color** [microDM/MicFunPred#9]
Hi! 

When I enter this code: git clone git@github.com:microDM/MicFunPred.git

The output says:

"git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

I'm not sure how to proceed. Thank you!

**Comment by microDM** [comment]
Please use public address to clone
`git clone https://github.com/microDM/MicFunPred.git`
